trainer:
  max_epochs: 3
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "ProgettoML"
      name: "head_oe_lambda5"
model:
  class_path: training.mask_classification_semantic_oe.MaskClassificationSemanticOE
  init_args:
    tuning_mode: "head"
    lambda_oe: 5.0
    attn_mask_annealing_enabled: True
    attn_mask_annealing_start_steps: [3317,8292,13268]
    attn_mask_annealing_end_steps: [6634,11609,16585]
    network:
      class_path: models.eomt.EoMT
      init_args:
        num_q: 100
        num_blocks: 3
        encoder:
          class_path: models.vit.ViT
          init_args:
            backbone_name: vit_base_patch14_reg4_dinov2
data:
  class_path: datasets.cityscapes_semantic_oe.CityscapesSemanticOE
  init_args:
    path: null
    contaminated_images: null
    anomaly_masks: null
    batch_size: 2
    img_size: [1024,1024]
    num_workers: 4